# frontend/Dockerfile
# Stage 1: Build React/Vite app
FROM node:22-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve với Nginx
FROM nginx:alpine
# Copy build từ stage 1 sang Nginx
COPY --from=build /app/dist /usr/share/nginx/html
# Mở port 80 (bên trong container)
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]